# Generated by Django 5.2.13 on 2026-05-04 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.restaurantcategory'),
        ),
        migrations.AddField(
            model_name='restaurantopeninghours',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='restaurants.restaurant'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['city', 'is_active', 'is_open'], name='restaurants_city_2ee11b_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['slug'], name='restaurants_slug_d8b6eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantopeninghours',
            unique_together={('restaurant', 'day_of_week')},
        ),
    ]
