# Generated by Django 5.2.13 on 2026-05-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='supports_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
