# Generated by Django 5.2.13 on 2026-07-09 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0003_courieravailabilitysession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierOperationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='simulation', max_length=32)),
                ('reference_id', models.CharField(blank=True, max_length=80)),
                ('completed_at', models.DateTimeField()),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-completed_at', '-id'),
                'indexes': [models.Index(fields=['courier', 'completed_at'], name='couriers_co_courier_95a065_idx'), models.Index(fields=['courier', 'source'], name='couriers_co_courier_db7862_idx')],
                'constraints': [models.UniqueConstraint(fields=('courier', 'source', 'reference_id'), name='unique_courier_operation_reference')],
            },
        ),
    ]
