# Generated by Codex on 2026-07-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("couriers", "0005_courieroperationentry_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="courierprofile",
            name="app_notifications_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="courierprofile",
            name="route_alerts_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="courierprofile",
            name="preferred_navigation_app",
            field=models.CharField(
                choices=[("google_maps", "Google Maps"), ("apple_maps", "Apple Maps"), ("waze", "Waze")],
                default="google_maps",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="courierprofile",
            name="app_language",
            field=models.CharField(default="ro", max_length=8),
        ),
        migrations.AddField(
            model_name="courierprofile",
            name="rating_average",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="courierprofile",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="CourierDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_card", "Identity card"),
                            ("driving_license", "Driving license"),
                            ("vehicle_registration", "Vehicle registration"),
                            ("insurance", "Insurance"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("missing", "Missing"),
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("review_note", models.TextField(blank=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courier_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("document_type",),
                "constraints": [
                    models.UniqueConstraint(fields=("courier", "document_type"), name="unique_courier_document_type"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CourierSupportTicket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=160)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("in_progress", "In progress"), ("closed", "Closed")],
                        default="open",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courier_support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(fields=("courier", "status"), name="couriers_co_courier_29d9cf_idx"),
                    models.Index(fields=("courier", "created_at"), name="couriers_co_courier_5eeb41_idx"),
                ],
            },
        ),
    ]
