# Generated by Django 5.2.13 on 2026-05-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='productoptiongroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='products.product'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='option_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.productoptiongroup'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['restaurant', 'is_available'], name='products_pr_restaur_da1c04_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_popular'], name='products_pr_is_popu_730ae0_idx'),
        ),
    ]
