# Generated by Django 5.2.13 on 2026-05-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_nutrition_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_audio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
