# Generated by Django 5.2.13 on 2026-06-10 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_audio_url_product_has_audio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='products.productcomment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='products.productcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='productcomment',
            index=models.Index(fields=['product', '-created_at'], name='products_pr_product_e649af_idx'),
        ),
        migrations.AddIndex(
            model_name='productcomment',
            index=models.Index(fields=['parent', 'created_at'], name='products_pr_parent__5ad221_idx'),
        ),
        migrations.AddIndex(
            model_name='productcommentlike',
            index=models.Index(fields=['comment', 'created_at'], name='products_pr_comment_a45b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='productcommentlike',
            index=models.Index(fields=['user', 'created_at'], name='products_pr_user_id_2e8ebe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcommentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AddIndex(
            model_name='productlike',
            index=models.Index(fields=['product', 'created_at'], name='products_pr_product_a31b18_idx'),
        ),
        migrations.AddIndex(
            model_name='productlike',
            index=models.Index(fields=['user', 'created_at'], name='products_pr_user_id_3f75df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productlike',
            unique_together={('product', 'user')},
        ),
    ]
