# Generated by Django 5.2.13 on 2026-06-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('burger', 'Burgeri'), ('shawarma', 'Shaorma'), ('asian', 'Asiatic'), ('sushi', 'Sushi'), ('pasta', 'Paste'), ('grill', 'Grill'), ('salad', 'Salate'), ('soup', 'Supe'), ('breakfast', 'Mic dejun'), ('dessert', 'Desert'), ('bakery', 'Panificație'), ('drinks', 'Băuturi'), ('seafood', 'Fructe de mare'), ('fish', 'Pește'), ('other', 'Altele')], default='other', max_length=32),
        ),
    ]
