# Generated by Django 5.2.13 on 2026-06-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredient_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
