# Generated by Django 5.2.13 on 2026-05-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='restaurants.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('restaurant', 'name')},
        ),
    ]
